
********************* VERSIONES *****************************
###
ORION VERSION
###
curl -X GET http://88.11.196.128:1026/version
curl -X GET http://192.168.1.41:1026/version
###
ENTIDADES DADAS DE ALTA EN ORION
###
curl -X GET "http://localhost:1026/v2/entities/"

###
SUBSCRIPCIONES EN ORION DE CYGNUS
###
http://localhost:1026/v2/subscriptions/
###

VERSION IOT AGENT 
###
curl -X GET "http://localhost:4041/iot/about"

###
VERSION IOT AGENT UL
###
curl -X GET "http://localhost:4061/iot/about"

###
CYGNUS VERSION
###
GET http://localhost:5080/v1/version

###
NIFI https
###
curl -X GET 'https://localhost:9090/nifi-api/system-diagnostics'

###
********************* ORION *****************************

ORION VERSION
###
GET http://localhost:1026/version
###
ENTIDADES DADAS DE ALTA EN ORION
curl -X GET "http://localhost:1026/v2/entities/"
###

AÑADIR ENTIDADES
###
curl -X POST 'http://localhost:1026/v2/entities/' 
-H 'Content-Type: application/json'
-d '{
        {
          "id": "Pamplona01",
          "type": "WeatherObserved",
          "address": {
            "addressLocality": "Pamplona",
            "addressCountry": "ES",
            "addressStreet":"Bernardino Tirapu 32"
          },
          "location": {
            "type": "Point",
            "coordinates": [
              -1.650774,
              42.825972
            ]
          },
          "temperature": 9,
          "atmosphericPressure": 938.9,
          "relativeHumidity": 1,
          "dateObserved": "2025-09-22T07:00:00.00Z",
          "windDirection": 135,
          "windSpeed": 2
        }
    }'
###
curl -X POST 'http://localhost:1026/v2/entities/' 
-H 'Content-Type: application/json' 
-d '{
        {
          "id": "Pamplona02",
          "type": "WeatherObserved",
          "address": {
            "addressLocality": "Pamplona",
            "addressCountry": "ES",
            "addressStreet":"Paseo Hemingway"
          },
          "location": {
            "type": "Point",
            "coordinates": [
              -1.640479,
              42.815890
            ]
          },
          "temperature": 9,
          "atmosphericPressure": 938.9,
          "relativeHumidity": 1,
          "dateObserved": "2025-09-22T07:00:00.00Z",
          "windDirection": 135,
          "windSpeed": 2,
        }
    }'


BUSCAR ENTIDADES POR ID 
###
curl -X GET http://localhost:1026/v2/entities/Room1?options=keyValues
###

http://localhost:1026/v2/entities/Room2?options=keyValues
###
http://localhost:1026/v2/entities/Room3?options=keyValues
###

************************************************************************
***********************************************************************
                          IoT Agent
************************************************************************
***********************************************************************

SABER SI EL SERVICIO ESTA FUNCIONANDO
curl -X GET 'http://localhost:4041/iot/about'

*************************************************************************

CONFIGURAR DISPOSITIVOS JSON EN ORION IOTs
curl -X POST "http://localhost:4041/iot/services" \
  -H "Content-Type: application/json" \
  -H "fiware-service: pamplona" \
  -H "fiware-servicepath: /" \
  -d '{
    "services": [{
      "apikey": "iot-json-key",
      "cbroker": "http://orion:1026",
      "entity_type": "Device",
      "resource": "/iot/json"
    }]
  }'



CONFIGURAR DISPOSITIVOS JSON EN ORION PARKING
curl -X POST "http://localhost:4041/iot/services" \
  -H "Content-Type: application/json" \
  -H "fiware-service: pamplona" \
  -H "fiware-servicepath: /parking" \
  -d '{
    "services": [{
      "apikey": "iot-json-key",
      "cbroker": "http://orion:1026",
      "entity_type": "Device",
      "resource": "/iot/parking",
      "attributes": [
        { "object_id": "t", "name": "temperature", "type": "Number" },
        { "object_id": "h", "name": "humidity", "type": "Number" }
      ]      
    }]
  }'
**********************************************************************
REGISTRAR DISPOSITIVOS JSON EN ORION

ROOM 1 IOTS SUBSERVICE
curl -X POST "http://localhost:4041/iot/devices" \
  -H "Content-Type: application/json" \
  -H "fiware-service: pamplona" \
  -H "fiware-servicepath: /iots" \
  -d '{
    "devices": [
      {
        "device_id": "sensorJSON001",
        "entity_name": "calidad_aire:sensorJSON001",
        "entity_type": "DeviceIoTJSON",
        "attributes": [
          { "object_id": "t", "name": "temperature", "type": "Number" },
          { "object_id": "h", "name": "humidity", "type": "Number" },
          { "object_id": "l", "name": "location", "type": "geo:json"}
        ],
        "protocol": "IoT-JSON",
        "apikey": "iot-json-key"
      }
    ]
  }'


ROOMPARKING001 PARKING SUBSERVICE
curl -X POST "http://localhost:4041/iot/devices" \
  -H "Content-Type: application/json" \
  -H "fiware-service: pamplona" \
  -H "fiware-servicepath: /parking" \
  -d '{
    "devices": [{
      "device_id": "roomparking001",
      "entity_name": "roomparking001",
      "entity_type": "Device",
      "attributes": [
        { "object_id": "t", "name": "temperature", "type": "Number" },
        { "object_id": "h", "name": "humidity", "type": "Number" }
      ],
      "protocol": "IoT-JSON",
      "apikey": "iot-json-key"
    }]
  }'


RECIBIR MEDIDAS
curl -iX POST \
  'http://localhost:7896/iot/json?k=iot-json-key&i=sensorJSON001' \
  -H 'Content-Type: application/json' \
  -d '{"t":23,"h":55,"l":"42.813288,-1.648511"}'

curl -X GET "http://localhost:1026/v2/entities" \
  -H "Fiware-Service: pamplona" \
  -H "Fiware-ServicePath: /iots"

curl -iX POST \
  'http://localhost:7896/iot/json?k=iot-json-key&i=roomparking001' \
  -H "Fiware-Service: pamplona" \
  -H "Fiware-ServicePath: /parking"
  -H 'Content-Type: application/json' \
  -d '{"t":25.5,"h":55}'

curl -X GET "http://localhost:1026/v2/entities" \
  -H "Fiware-Service: pamplona" \
  -H "Fiware-ServicePath: /parking"



*****************************************************************
************************************************************************
***********************************************************************
                          IoT Agent UL
************************************************************************
***********************************************************************
----------------------------------------------------------------------
----------------------------------------------------------------------
REGISTRAR UN SERVICIO DE IOT-UL AIR QUALITY
----------------------------------------------------------------------
----------------------------------------------------------------------
curl -iX POST 'http://localhost:4061/iot/services' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: pamplona' \
  -H 'fiware-servicepath: /' \
  -d '{
 "services": [
   {
     "apikey":      "iot-json-key",
     "cbroker":     "http://orion:1026",
     "entity_type": "Device",
     "resource":    "/iot/d"
   }
 ]
}'


curl -iX POST 'http://localhost:4061/iot/services' \
-H 'fiware-service: pamplonaul' \
-H 'fiware-servicepath: /' \
-H 'Content-Type: application/json' \
--data-raw '{
    "services": [
        {
          "apikey": "4jggokgpepnvsb2uv4s40d59ov",
          "cbroker": "http://orion:1026",
          "entity_type": "Device",
          "resource": "/iot/d"
        }
    ]
}'

REGISTRAR UN SENSOR IOT UL

curl -L -X POST 'http://localhost:4061/iot/devices' \
    -H 'fiware-service: pamplona' \
    -H 'fiware-servicepath: /' \
    -H 'Content-Type: application/json' \
--data-raw '{
  "devices": [
    {
      "device_id": "temperature007",
      "entity_name": "temperature007",
      "entity_type": "Device",
      "apikey": "4jggokgpepnvsb2uv4s40d59ov",
      "timezone": "Europe/Berlin",
      "attributes": [
        {
          "object_id": "t",
          "name": "temperature",
          "type": "Number"
        }
      ]
    }
  ]
}'

http://iot-agent:7896/iot/d?i=temperature001&k=4jggokgpepnvsb2uv4s40d59ov

curl -L -X POST 'http://localhost:7897/iot/d?k=4jggokgpepnvsb2uv4s40d59ov&i=temperature007' \
    -H 'Content-Type: text/plain' \
    --data-raw 't|24'

curl -X POST 'http://localhost:4061/iot/devices' \
  -H "Content-Type: application/json" \
  -H "fiware-service: pamplona" \
  -H "fiware-servicepath: /" \
  -d '{
  "devices": [
    {
      "device_id": "AirQuality0001",
      "entity_name": "AirQuality0001",
      "entity_type": "AirQuality",
      "protocol":    "IoTA-UltraLight",
      "transport":   "HTTP",
      "attributes": [
        { "object_id": "t", "name": "temperature", "type": "Integer" },
        { "object_id": "h", "name": "humidity", "type": "Integer" },
        { "object_id": "q", "name": "airquality", "type": "Integer" },
        { "object_id": "l", "name": "location", "type": "geo:json" }
      ],
      "static_attributes": [
        { "name": "temperature", "type": "Integer", "value": 0 },
        { "name": "humidity", "type": "Integer", "value": 0 },
        { "name": "airquality", "type": "Integer", "value": 0 },
        { "name": "location", "type": "Text", "value": "0,0" }
      ],
      "apikey": "iot-json-key",
      "autocreate": true
    }
  ]
}' 

curl -X POST 'http://localhost:4061/iot/devices' \
  -H "Content-Type: application/json" \
  -H "fiware-service: pamplona" \
  -H "fiware-servicepath: /" \
  -d '{
  "devices": [
    {
      "device_id": "AirQuality0002",
      "entity_name": "AirQuality0002",
      "entity_type": "AirQuality",
      "protocol":    "IoTA-UltraLight",
      "transport":   "HTTP",
      "attributes": [
        { "object_id": "t", "name": "temperature", "type": "Integer" },
        { "object_id": "h", "name": "humidity", "type": "Integer" },
        { "object_id": "q", "name": "airquality", "type": "Integer" },
        { "object_id": "l", "name": "location", "type": "geo:json" }
      ],
      "static_attributes": [
        { "name": "temperature", "type": "Integer", "value": 0 },
        { "name": "humidity", "type": "Integer", "value": 0 },
        { "name": "airquality", "type": "Integer", "value": 0 },
        { "name": "location", "type": "Text", "value": "0,0" }
      ],
      "apikey": "iot-json-key"
    }
  ]
}' 


curl -iX POST "http://iot-agent:7896/iot/d?i=AirQuality0001&k=iot-json-key"

ASIGNAR/CAMBIAR DATOS
curl -iX POST 'http://localhost:7897/iot/ul?k=iot-json-key&i=AirQuality0001'
  -H 'Content-Type:text/plain' \
  -H "Fiware-Service: pamplona" \
  -H "Fiware-ServicePath: /" \
  -d 't|34|h|50|q|3|gps|42.812847,-1.642932'

curl -iX POST 'http://localhost:7896/iot/ul?k=iot-json-key&i=AirQuality0002'
  -H 'Content-Type:text/plain' \
  -H "Fiware-Service: iot_ul_service" \
  -H "Fiware-ServicePath: /iot_ul" \
  -d 't|23|h|55|q|3|gps|42.813288,-1.648511'


SABER SI LAS ENTIDADES EN ORION SE CREAN BIEN
curl -X GET "http://localhost:1026/v2/entities" \
  -H "Fiware-Service: iot_ul_service" \
  -H "Fiware-ServicePath: /iot_ul"

SABER SI LAS ENTIDADES EN ORION SE CREAN BIEN
curl -X GET "http://localhost:1026/v2/types" \
  -H "Fiware-Service: iot_ul_service" \
  -H "Fiware-ServicePath: /iot_ul"



*******************STH COMET**************************

curl -X GET "http://0.0.0.0:8666/notify"

curl -X GET "http://localhost:8666/version"

http://localhost:8090/

curl -X GET \
  'http://sth-comet:8666/version'

curl -X GET "http://localhost:8666/STH/v1/"
curl -X GET "http://localhost:8666/STH/v1/contextEntities/type/Device/id/room001/attributes/temperature" \
  -H "Accept: application/json" \
  -H "Fiware-Service: pamplona" \
  -H "Fiware-ServicePath: /iots"



curl -X GET "http://localhost:8666/STH/v2/entities/room001/attrs/temperature?type=Device&hLimit=3&hOffset=0&dateFrom=2024-01-01T00:00:00.000Z&dateTo=2026-01-01T23:59:59.999Z" \
-H "Fiware-Service: pamplona" \
  -H "Fiware-ServicePath: /iots"

curl -X GET "http://localhost:8666/STH/v2/entities/room001/attrs/temperature?type=Device&hLimit=3&hOffset=0&dateFrom=2024-01-01T00:00:00.000Z&dateTo=2026-01-01T23:59:59.999Z" \
  -H "Fiware-Service: pamplona" \
  -H "Fiware-ServicePath: /iots"

curl -X GET "http://localhost:8666/STH/v2/contextEntities/room001"
 -H "Accept: application/json" \
  -H "Fiware-Service: pamplona" \
  -H "Fiware-ServicePath: /iots"

curl -X GET "http://localhost:1026/v2/subscriptions" 
  -H "Accept: application/json"
  -H "Fiware-Service: pamplona" \
  -H "Fiware-ServicePath: /iots"

  curl -X POST "http://localhost:1026/v2/subscriptions" \
  -H "Content-Type: application/json" \
  -d '{
    "description": "Suscripción para guardar histórico en STH-Comet",
    "subject": {
      "entities": [
        { "idPattern": ".*"}
      ]
    },
    "notification": {
      "http": {
        "url": "http://sth-comet:8666/notify"
      },
      "attrsFormat": "keyValues"
    },
    "expires": "2040-01-01T00:00:00.00Z",
    "throttling": 0
  }'


curl -X GET "http://localhost:8666/STH/v1/contextEntities/type/AirQuality/id/AirQuality0001/attributes/Temperature?lastN=10" \
  -H "Fiware-Service: iot_ul_service" \
  -H "Fiware-ServicePath: /iot_ul"

curl -X GET "http://localhost:8666/v1/" 


******************* CYGNUS******************************

CYGNUS VERSION
http://localhost:5080/v1/version

SUBSCRIPCIONES EN ORION DE CYGNUS
curl -X GET " http://localhost:1026/v2/subscriptions/"\
  -H "Fiware-Service: pamplona" \
  -H "Fiware-ServicePath: /iots"

CREAR SUBCRIPCION MONGO
curl -X POST 'http://localhost:1026/v2/subscriptions/'
-H 'Content-Type: application/json' 
-H "Fiware-Service: iot_room" 
-H "Fiware-ServicePath: /movilidad"
-d '{
  "description": "Notify Cygnus of all context changes",
  "subject": {
    "entities": [
      {
        "idPattern": ".*"
      }
    ]
  },
  "notification": {
    "http": {
      "url": "http://cygnus:5051/notify"
    }
  },
  "throttling": 0
}'


SUBCRIPCION PARA POSTGRES
curl -X POST 'http://localhost:1026/v2/subscriptions'
  -H 'Content-Type: application/json' 
  -H "Fiware-Service: pamplona" 
  -H "Fiware-ServicePath: /" \
-d '{
  "description": "Notify Cygnus of changes in IoT Agent",
  "subject": {
    "entities": [
      {
        "idPattern": ".*",
        "type": "Device"
      }
    ]
  },
  "notification": {
    "http": {
      "url": "http://cygnus:5055/notify"
    }
  },
  "throttling": 0
}'


curl -iX POST \
  'http://localhost:1026/v2/subscriptions' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: pamplona' \
  -H 'fiware-servicepath: /movilidad' \
  -d '{
  "description": "Notify Cygnus of all context changes",
  "subject": {
    "entities": [
      {
        "idPattern": ".*"
      }
    ]
  },
  "notification": {
    "http": {
      "url": "http://cygnus:5050/notify"
    }
  },
  "throttling": 0
}'

curl -iX POST \
  'http://localhost:1026/v2/subscriptions' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: pamplona' \
  -H 'fiware-servicepath: /iot' \
  -d '{
  "description": "Notify nifi of all context changes",
  "subject": {
    "entities": [
      {
        "idPattern": ".*"
      }
    ]
  },
  "notification": {
    "http": {
      "url": "http://cygnus:5050/notify"
    }
  },
  "throttling": 0
}'

**************************************************************************

curl -X GET 'http://localhost:1026/v2/subscriptions'


curl -X GET "http://localhost:1026/v2/entities/"

curl -X GET 'http://localhost:4041/iot/about'

http://localhost:1026/v2/entities/Room1?options=keyValues
http://localhost:1026/v2/entities/?options=keyValues

ACTUALIZAR DATOS ENTIDAD 
curl -iX POST 'http://localhost:1026/v2/entities/room001/attrs' \
  -H 'Content-Type: application/json' \
  -H "Fiware-Service: pamplona" \
  -H "Fiware-ServicePath: /iots"
-d '
{
    "temperature": {"value": 30}
}'

curl -X PATCH 'http://localhost:1026/v2/entities/Room1/attrs' \
-H 'Content-Type: application/json' \
-d '{
  "temperature": {
    "value": 66
  }
}'

curl -X PATCH 'http://localhost:1026/v2/entities/Room2/attrs' \
-H 'Content-Type: application/json' \
-d '{
  "temperature": {
    "value": 44
  }
}'



